# Generated by Django 3.2.9 on 2023-01-26 22:17

import budget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(choices=[('default', 'DEFAULT'), ('choosing_category', 'CHOOSING_CATEGORY'), ('entering_expense', 'ENTERING_EXPENSE'), ('entering_expense_more_than_one', 'ENTERING_EXPENSE_MORE_THAN_ONE'), ('expense_entered', 'EXPENSE_ENTERED'), ('entering_email', 'ENTERING_EMAIL')], default=budget.models.UserStatusEnum['DEFAULT'], max_length=56),
        ),
    ]
