# Generated by Django 3.2.9 on 2023-01-28 12:15

import budget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_userstatus_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(choices=[('default', 'DEFAULT'), ('choosing_category', 'CHOOSING_CATEGORY'), ('entering_expense', 'ENTERING_EXPENSE'), ('entering_expense_more_than_one', 'ENTERING_EXPENSE_MORE_THAN_ONE'), ('batch_entering_expense', 'BATCH_ENTERING_EXPENSE'), ('expense_entered', 'EXPENSE_ENTERED'), ('entering_email', 'ENTERING_EMAIL')], default=budget.models.UserStatusEnum['DEFAULT'], max_length=56),
        ),
    ]
