# Generated by Django 3.2.9 on 2023-01-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_message',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
