# Generated by Django 3.2.9 on 2023-01-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_spreadsheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spreadsheet_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
