# Generated by Django 3.2.9 on 2023-01-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_spreadsheet_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='spreadsheet_title',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
